"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os 
from datetime import timedelta



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# ────────────────────
# Quick‑start settings
# ────────────────────
SECRET_KEY = "django-insecure-n+a=lq4ty!i)x70vv5foercfm5w^lw0a^ifibwemq9@u0jdrg_"
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]          # ← add hosts you’ll run on


# ────────────────────
# Applications
# ────────────────────
INSTALLED_APPS = [
    # Django defaults
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third‑party
    "rest_framework",
    "rest_framework_simplejwt",     # ← NEW
    "corsheaders",

    # Project apps
    "accounts",
    "courses",
    "enrollments",
    "reviews",
]


# ────────────────────
# Middleware
# ────────────────────
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",        # keep CORS first
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ────────────────────
# URLs / WSGI
# ────────────────────
ROOT_URLCONF = "backend.urls"
WSGI_APPLICATION = "backend.wsgi.application"


# ────────────────────
# Templates
# ────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ────────────────────
# Database (SQLite for dev)
# ────────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ────────────────────
# Password validation
# ────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ────────────────────
# Internationalization
# ────────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ────────────────────
# Static files
# ────────────────────
STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ────────────────────
# CORS
# ────────────────────
CORS_ALLOW_ALL_ORIGINS = True      # dev‑only; tighten for production


# ────────────────────
# REST Framework / JWT
# ────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Uncomment the line below if you want every view protected by default.
    # "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

# Use your custom user model from accounts app
AUTH_USER_MODEL = "accounts.CustomUser"
